//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapgeminiVoting {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapgeminiVoting.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add answer.
        /// </summary>
        public static string Add_answer {
            get {
                return ResourceManager.GetString("Add_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add question.
        /// </summary>
        public static string Add_question {
            get {
                return ResourceManager.GetString("Add_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to event list.
        /// </summary>
        public static string Back_to_event_list {
            get {
                return ResourceManager.GetString("Back_to_event_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkboxes.
        /// </summary>
        public static string Checkboxes {
            get {
                return ResourceManager.GetString("Checkboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new event.
        /// </summary>
        public static string Create_new_event {
            get {
                return ResourceManager.GetString("Create_new_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your answer.
        /// </summary>
        public static string Enter_answer {
            get {
                return ResourceManager.GetString("Enter_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your question.
        /// </summary>
        public static string Enter_question {
            get {
                return ResourceManager.GetString("Enter_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event ID should be numeric..
        /// </summary>
        public static string Err_event_not_numeric {
            get {
                return ResourceManager.GetString("Err_event_not_numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No event code filled in..
        /// </summary>
        public static string Err_no_event_code {
            get {
                return ResourceManager.GetString("Err_no_event_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No questions found for this event ID..
        /// </summary>
        public static string Err_no_questions_found_for_event {
            get {
                return ResourceManager.GetString("Err_no_questions_found_for_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question not found for this event..
        /// </summary>
        public static string Err_question_not_found_for_event {
            get {
                return ResourceManager.GetString("Err_question_not_found_for_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update your answer on the database..
        /// </summary>
        public static string Err_unable_to_update_answer_on_db {
            get {
                return ResourceManager.GetString("Err_unable_to_update_answer_on_db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event list.
        /// </summary>
        public static string Event_list_title {
            get {
                return ResourceManager.GetString("Event_list_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event result.
        /// </summary>
        public static string Event_result_title {
            get {
                return ResourceManager.GetString("Event_result_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free text.
        /// </summary>
        public static string Free_text {
            get {
                return ResourceManager.GetString("Free_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify event.
        /// </summary>
        public static string Modify_event {
            get {
                return ResourceManager.GetString("Modify_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All questions have been processed..
        /// </summary>
        public static string Msg_all_questions_processed {
            get {
                return ResourceManager.GetString("Msg_all_questions_processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple choice.
        /// </summary>
        public static string Multiple_choice {
            get {
                return ResourceManager.GetString("Multiple_choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a description.
        /// </summary>
        public static string New_event_description {
            get {
                return ResourceManager.GetString("New_event_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the end date.
        /// </summary>
        public static string New_event_end_date {
            get {
                return ResourceManager.GetString("New_event_end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an event name.
        /// </summary>
        public static string New_event_name {
            get {
                return ResourceManager.GetString("New_event_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the start date.
        /// </summary>
        public static string New_event_start_date {
            get {
                return ResourceManager.GetString("New_event_start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit event.
        /// </summary>
        public static string New_event_submit {
            get {
                return ResourceManager.GetString("New_event_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible answers.
        /// </summary>
        public static string Possible_answers {
            get {
                return ResourceManager.GetString("Possible_answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh in:.
        /// </summary>
        public static string Refresh_in {
            get {
                return ResourceManager.GetString("Refresh_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select question:.
        /// </summary>
        public static string Select_question {
            get {
                return ResourceManager.GetString("Select_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mailto:&amp;subject=Capgemini Voting App: Code to vote&amp;body=Dear Colleague,%0D%0A %0D%0AI am pleased to invite you to join the following event on the Voting app:%0D%0A  Event name: {0} %0D%0A  Event description: {1} %0D%0A  Event ID: {2} %0D%0A%0D%0AYou can reach the Voting app via www.CapgeminiSuperVoting.com %0D%0A%0D%0AKind regards.
        /// </summary>
        public static string shareEventMail {
            get {
                return ResourceManager.GetString("shareEventMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Table_code {
            get {
                return ResourceManager.GetString("Table_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string Table_creationdate {
            get {
                return ResourceManager.GetString("Table_creationdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Table_description {
            get {
                return ResourceManager.GetString("Table_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Table_name {
            get {
                return ResourceManager.GetString("Table_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
    }
}
