//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapgeminiVoting {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapgeminiVoting.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add answer.
        /// </summary>
        public static string Add_answer {
            get {
                return ResourceManager.GetString("Add_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add question.
        /// </summary>
        public static string Add_question {
            get {
                return ResourceManager.GetString("Add_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of voters.
        /// </summary>
        public static string Amount_of_voters {
            get {
                return ResourceManager.GetString("Amount_of_voters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to event list.
        /// </summary>
        public static string Back_to_event_list {
            get {
                return ResourceManager.GetString("Back_to_event_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capgemini Voting.
        /// </summary>
        public static string Capgemini_Voting {
            get {
                return ResourceManager.GetString("Capgemini_Voting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkboxes.
        /// </summary>
        public static string Checkboxes {
            get {
                return ResourceManager.GetString("Checkboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to log in..
        /// </summary>
        public static string Click_here_to_log_in {
            get {
                return ResourceManager.GetString("Click_here_to_log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm e-mail.
        /// </summary>
        public static string Confirm_email {
            get {
                return ResourceManager.GetString("Confirm_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new event.
        /// </summary>
        public static string Create_new_event {
            get {
                return ResourceManager.GetString("Create_new_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail link.
        /// </summary>
        public static string Email_link {
            get {
                return ResourceManager.GetString("Email_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your answer.
        /// </summary>
        public static string Enter_answer {
            get {
                return ResourceManager.GetString("Enter_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your question.
        /// </summary>
        public static string Enter_question {
            get {
                return ResourceManager.GetString("Enter_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event ID is not valid..
        /// </summary>
        public static string Err_event_not_numeric {
            get {
                return ResourceManager.GetString("Err_event_not_numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No event code filled in..
        /// </summary>
        public static string Err_no_event_code {
            get {
                return ResourceManager.GetString("Err_no_event_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No questions found for this event ID..
        /// </summary>
        public static string Err_no_questions_found_for_event {
            get {
                return ResourceManager.GetString("Err_no_questions_found_for_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question not found for this event..
        /// </summary>
        public static string Err_question_not_found_for_event {
            get {
                return ResourceManager.GetString("Err_question_not_found_for_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update your answer on the database..
        /// </summary>
        public static string Err_unable_to_update_answer_on_db {
            get {
                return ResourceManager.GetString("Err_unable_to_update_answer_on_db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event list.
        /// </summary>
        public static string Event_list_title {
            get {
                return ResourceManager.GetString("Event_list_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This event is locked.
        /// </summary>
        public static string Event_locked {
            get {
                return ResourceManager.GetString("Event_locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event result.
        /// </summary>
        public static string Event_result_title {
            get {
                return ResourceManager.GetString("Event_result_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event successfully created.
        /// </summary>
        public static string Event_successfully_created {
            get {
                return ResourceManager.GetString("Event_successfully_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event successfully modified.
        /// </summary>
        public static string Event_successfully_modified {
            get {
                return ResourceManager.GetString("Event_successfully_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event successfully removed.
        /// </summary>
        public static string Event_successfully_removed {
            get {
                return ResourceManager.GetString("Event_successfully_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password.
        /// </summary>
        public static string Forgot_password {
            get {
                return ResourceManager.GetString("Forgot_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password confirmation.
        /// </summary>
        public static string Forgot_password_confirmation {
            get {
                return ResourceManager.GetString("Forgot_password_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string Forgot_your_password {
            get {
                return ResourceManager.GetString("Forgot_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free text.
        /// </summary>
        public static string Free_text {
            get {
                return ResourceManager.GetString("Free_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Log_in {
            get {
                return ResourceManager.GetString("Log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This e-mail address has already been registered.
        /// </summary>
        public static string Mail_already_registered {
            get {
                return ResourceManager.GetString("Mail_already_registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify event.
        /// </summary>
        public static string Modify_event {
            get {
                return ResourceManager.GetString("Modify_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All questions have been processed..
        /// </summary>
        public static string Msg_all_questions_processed {
            get {
                return ResourceManager.GetString("Msg_all_questions_processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple choice.
        /// </summary>
        public static string Multiple_choice {
            get {
                return ResourceManager.GetString("Multiple_choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a description.
        /// </summary>
        public static string New_event_description {
            get {
                return ResourceManager.GetString("New_event_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the end date.
        /// </summary>
        public static string New_event_end_date {
            get {
                return ResourceManager.GetString("New_event_end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an event name.
        /// </summary>
        public static string New_event_name {
            get {
                return ResourceManager.GetString("New_event_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the start date.
        /// </summary>
        public static string New_event_start_date {
            get {
                return ResourceManager.GetString("New_event_start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit event.
        /// </summary>
        public static string New_event_submit {
            get {
                return ResourceManager.GetString("New_event_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No answers were found for this question..
        /// </summary>
        public static string No_answers_found_for_question {
            get {
                return ResourceManager.GetString("No_answers_found_for_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not your event!.
        /// </summary>
        public static string Not_your_event {
            get {
                return ResourceManager.GetString("Not_your_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset..
        /// </summary>
        public static string Password_reset {
            get {
                return ResourceManager.GetString("Password_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        public static string Please_check_mail_to_reset_password {
            get {
                return ResourceManager.GetString("Please_check_mail_to_reset_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your e-mail address first..
        /// </summary>
        public static string Please_confirm_email {
            get {
                return ResourceManager.GetString("Please_confirm_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify at least two answers for the questions which don&apos;t expect free text answers.
        /// </summary>
        public static string Please_specify_answer {
            get {
                return ResourceManager.GetString("Please_specify_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify at least one question for your event.
        /// </summary>
        public static string Please_specify_question {
            get {
                return ResourceManager.GetString("Please_specify_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible answers.
        /// </summary>
        public static string Possible_answers {
            get {
                return ResourceManager.GetString("Possible_answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh in:.
        /// </summary>
        public static string Refresh_in {
            get {
                return ResourceManager.GetString("Refresh_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string Register_as_new_user {
            get {
                return ResourceManager.GetString("Register_as_new_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration succeeded. An e-mail has been sent to activate your account..
        /// </summary>
        public static string Registration_succeeded {
            get {
                return ResourceManager.GetString("Registration_succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string Reset_password {
            get {
                return ResourceManager.GetString("Reset_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password confirmation.
        /// </summary>
        public static string Reset_password_confirmation {
            get {
                return ResourceManager.GetString("Reset_password_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select question:.
        /// </summary>
        public static string Select_question {
            get {
                return ResourceManager.GetString("Select_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mailto:&amp;subject=Capgemini Voting: Code to vote&amp;body=Dear Colleague,%0D%0A %0D%0AI am pleased to invite you to join the following event on the Capgemini Voting website:%0D%0A  Event name: {0} %0D%0A  Event description: {1} %0D%0A  Event ID: {2} %0D%0A%0D%0AYou can reach the Capgemini Voting website via http://capvoting.azurewebsites.net/ %0D%0A%0D%0AKind regards, %0D%0A%0D%0A CodingNights Team.
        /// </summary>
        public static string shareEventMail {
            get {
                return ResourceManager.GetString("shareEventMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Table_code {
            get {
                return ResourceManager.GetString("Table_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string Table_creationdate {
            get {
                return ResourceManager.GetString("Table_creationdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Table_description {
            get {
                return ResourceManager.GetString("Table_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Table_name {
            get {
                return ResourceManager.GetString("Table_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your e-mail..
        /// </summary>
        public static string Thanks_for_confirming_email {
            get {
                return ResourceManager.GetString("Thanks_for_confirming_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your events.
        /// </summary>
        public static string Your_events {
            get {
                return ResourceManager.GetString("Your_events", resourceCulture);
            }
        }
    }
}
