//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapgeminiVoting {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapgeminiVoting.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add answer.
        /// </summary>
        public static string Add_answer {
            get {
                return ResourceManager.GetString("Add_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add question.
        /// </summary>
        public static string Add_question {
            get {
                return ResourceManager.GetString("Add_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkboxes.
        /// </summary>
        public static string Checkboxes {
            get {
                return ResourceManager.GetString("Checkboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new event.
        /// </summary>
        public static string Create_new_event {
            get {
                return ResourceManager.GetString("Create_new_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your answer.
        /// </summary>
        public static string Enter_answer {
            get {
                return ResourceManager.GetString("Enter_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your question.
        /// </summary>
        public static string Enter_question {
            get {
                return ResourceManager.GetString("Enter_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event list.
        /// </summary>
        public static string Event_list_title {
            get {
                return ResourceManager.GetString("Event_list_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free text.
        /// </summary>
        public static string Free_text {
            get {
                return ResourceManager.GetString("Free_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple choice.
        /// </summary>
        public static string Multiple_choice {
            get {
                return ResourceManager.GetString("Multiple_choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a description.
        /// </summary>
        public static string New_event_description {
            get {
                return ResourceManager.GetString("New_event_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the end date.
        /// </summary>
        public static string New_event_end_date {
            get {
                return ResourceManager.GetString("New_event_end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an event name.
        /// </summary>
        public static string New_event_name {
            get {
                return ResourceManager.GetString("New_event_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the start date.
        /// </summary>
        public static string New_event_start_date {
            get {
                return ResourceManager.GetString("New_event_start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit event.
        /// </summary>
        public static string New_event_submit {
            get {
                return ResourceManager.GetString("New_event_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible answers.
        /// </summary>
        public static string Possible_answers {
            get {
                return ResourceManager.GetString("Possible_answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Table_code {
            get {
                return ResourceManager.GetString("Table_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Table_description {
            get {
                return ResourceManager.GetString("Table_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string Table_enddate {
            get {
                return ResourceManager.GetString("Table_enddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Table_name {
            get {
                return ResourceManager.GetString("Table_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string Table_startdate {
            get {
                return ResourceManager.GetString("Table_startdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
    }
}
